package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"log"
	"os"

	"github.com/caiquetorres/lumi/internal/emitter"
	"github.com/caiquetorres/lumi/internal/lexer"
	"github.com/caiquetorres/lumi/internal/parser"
	"github.com/caiquetorres/lumi/internal/semantic"
	"github.com/caiquetorres/lumi/internal/vm"
)

func main() {
	args := parseArgs()
	log.Printf("running with file: %s", args.filePath)

	f, err := os.Open(args.filePath)
	if err != nil {
		log.Fatal(err)
	}

	err = os.Remove(args.outPath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		log.Fatal(err)
	}

	o, err := os.Create(args.outPath)
	if err != nil {
		log.Fatal(err)
	}

	if err := runPipeline(f, o, args.debug); err != nil {
		log.Fatal(err)
	}
}

func runPipeline(src io.Reader, out io.Writer, debugMode bool) error {
	var (
		l = lexer.New(src)
		p = parser.New(src, l)
	)

	ast, err := p.Parse()
	if err != nil {
		return err
	}

	if debugMode {
		fmt.Println("Parsed AST:")
		if err := parser.DebugAst(ast, l, os.Stdout); err != nil {
			return err
		}
		fmt.Println("")
	}

	if err := semantic.Analyze(ast); err != nil {
		return err
	}

	if err := emitter.Emit(ast, l, out); err != nil {
		return err
	}

	if debugMode {
		var buf bytes.Buffer
		if err := emitter.Emit(ast, l, &buf); err != nil {
			return err
		}

		fmt.Println("Generated bytecode:")
		formatBytecode(os.Stdout, &buf)
		fmt.Println("")
	}

	if err := vm.Execute(); err != nil {
		return err
	}

	return nil
}

func formatBytecode(w io.Writer, r io.Reader) {
	code, _ := io.ReadAll(r)

	if len(code) == 0 {
		return
	}

	for idx, b := range code {
		if idx > 0 {
			w.Write([]byte{' '})
		}

		_, _ = fmt.Fprintf(w, "0x%02X", b)
	}
}
